export const CHANGE_CLUE = 'CHANGE_CLUE';
export const GET_SUGGESTIONS = 'GET_SUGGESTIONS';
export const SET_CURSOR = 'SET_CURSOR';
export const SET_CURSOR_DIRECTION = 'SET_CURSOR_DIRECTION';
export const TOGGLE_CURSOR_DIRECTION = 'TOGGLE_CURSOR_DIRECTION';
