// Type for object with arbitrary keys, which  may be numbers,
// which in some cases will be returned from the firebase sdk as an array
export type FirebaseArray<T, K extends string = string> = Record<K, T> | T[];
// Map type for objects with keys generated by push, which provide order but
// are not numeric and come from firebase as objects
export type FirebaseList<T, K extends string = string> = Record<K, T>;
export type FirebaseValue = boolean | string | number | Object | null;
export type FirebaseReadValue<T extends FirebaseValue = FirebaseValue> =
  | T
  | undefined;
