import type { Metadata } from "next";
import "./globals.css";
import { ConnectedHeader } from "../components/Header";
import { FirebaseUIProvider } from "../firebase/ui/FirebaseUIProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <FirebaseUIProvider>
          <ConnectedHeader />
          {children}
        </FirebaseUIProvider>
      </body>
    </html>
  );
}
