import type { Metadata } from "next";
import { Root } from "../recoil";
import "./globals.css";
import { ConnectedHeader } from "../components/Header";
import { LoginProtector } from "../components/LoginProtector";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Root>
      <html lang="en">
        <body>
          <ConnectedHeader />
          <LoginProtector>{children}</LoginProtector>
        </body>
      </html>
    </Root>
  );
}
