// General type for object with arbitrary keys, which  may be numbers,
// which in some cases will be returned from the firebase sdk as an array
export type FirebaseArray<T, K extends string = string> = Record<K, T> | T[];
// Map type for objects with keys generated by push, which provide order but
// are not numeric and come from firebase as objects
// TODO how does this relate to the lack of order guarantee in javascript object keys?
export type FirebaseList<T, K extends string = string> = Record<K, T>;
export type Matrix<Type> = FirebaseArray<FirebaseArray<Type>>;
export type Presence<Type extends string> = FirebaseArray<boolean, Type>;
export type CurrentUser = UserId;
export type FirebaseValue = boolean | string | number | Object | null;
export type FirebaseReadValue<T extends FirebaseValue = FirebaseValue> =
  | T
  | undefined;

export type Clues = {
  across?: Matrix<string>;
  down?: Matrix<string>;
};
export type Crossword = {
  rows: number;
  symmetric: boolean;
  themeEntries?: Presence<string>;
  clues?: Clues;
  boxes?: Matrix<Box>;
  title?: string;
};
export type Index = string;
export type Direction = string;
export type Box = {
  blocked?: boolean;
  circled?: boolean;
  shaded?: boolean;
  content?: string;
};
export type CrosswordMetadata = {
  title?: string;
};
export type WordlistEntry = {
  word: string;
  usedBy?: Presence<CrosswordId>;
};
export type User = {
  crosswords?: FirebaseList<CrosswordMetadata>;
  wordlist?: FirebaseList<WordlistEntry>;
};
export type Permissions = {
  owner: UserId;
  collaborators?: Presence<UserId>;
  global?: boolean;
  readonly?: boolean;
};
export type UserId = string;
export type CrosswordId = string;
export type Cursor = {
  userId: CurrentUser;
  row?: number;
  column?: number;
  displayName?: string;
  photoURL?: string;
  color?: string;
};
export type CommunalCrossword = {
  current: CrosswordId;
  archive?: FirebaseList<CrosswordId>;
};
